/* ==========================================================================
   make.js — build one streamer's own copy of the pack.

     node make.js nikos           → dist/nikos/
     node make.js nikos --zip     → dist/nikos/ and dist/nikos.zip
     node make.js --all           → every client in clients/

   It reads clients/<name>.json, copies the pack, bakes in that person's skin
   and settings, and writes them a ΟΔΗΓΙΕΣ.md with their exact OBS sources.
   The result is self-contained: they can run it with no internet except the
   Google Fonts and Twitch emote requests the overlays already make.
   ========================================================================== */

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = __dirname;
const OVERLAY_FILES = ['alerts.html', 'goal.html', 'chat.html', 'labels.html', 'scene.html'];

/* Defaults used when a client file leaves something out. */
const DEFAULT_OVERLAYS = {
  alerts: { file: 'overlays/alerts.html', params: 'pos=top-center', size: '1920 × 1080',
            title: 'Alerts' },
  goal:   { file: 'overlays/goal.html',   params: 'pos=bottom-left', size: '500 × 160',
            title: 'Goal bar' },
  chat:   { file: 'overlays/chat.html',   params: 'pos=bottom-left', size: '500 × 900',
            title: 'Chat box' },
  labels: { file: 'overlays/labels.html', params: 'pos=bottom-right', size: '320 × 130',
            title: 'Labels' },
  scene:  { file: 'overlays/scene.html',  params: 'mode=starting&t=300', size: '1920 × 1080',
            title: 'Starting soon' }
};

/* --- helpers ------------------------------------------------------------ */

function die(message) {
  console.error('\n  ✗ ' + message + '\n');
  process.exit(1);
}

function readClient(name) {
  const file = path.join(root, 'clients', name + '.json');
  if (!fs.existsSync(file)) die('Δεν βρέθηκε το clients/' + name + '.json');
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    die('Το clients/' + name + '.json δεν είναι έγκυρο JSON: ' + err.message);
  }
}

/* Patch a file in place with a list of [find, replace] pairs. */
function patch(file, pairs) {
  let text = fs.readFileSync(file, 'utf8');
  for (const [find, replace] of pairs) text = text.replace(find, replace);
  fs.writeFileSync(file, text, 'utf8');
}

/* --- build one client ---------------------------------------------------- */

function build(name, options) {
  const client = readClient(name);
  const skin = client.skin || 'default';
  const out = path.join(root, 'dist', name);

  if (!fs.existsSync(path.join(root, 'skins', skin, 'skin.css'))) {
    die('Το skin "' + skin + '" δεν υπάρχει στο skins/');
  }

  /* 1. clean slate, then copy the parts a streamer actually needs */
  fs.rmSync(out, { recursive: true, force: true });
  fs.mkdirSync(out, { recursive: true });

  for (const dir of ['css', 'js', 'overlays', 'assets']) {
    const from = path.join(root, dir);
    if (fs.existsSync(from)) fs.cpSync(from, path.join(out, dir), { recursive: true });
  }
  /* only their skin travels with them, plus default as the fallback */
  fs.mkdirSync(path.join(out, 'skins'), { recursive: true });
  for (const s of new Set([skin, 'default'])) {
    fs.cpSync(path.join(root, 'skins', s), path.join(out, 'skins', s), { recursive: true });
  }
  for (const f of ['index.html', 'serve.js', 'start.cmd']) {
    fs.copyFileSync(path.join(root, f), path.join(out, f));
  }
  /* the template is a working note for us, not for them */
  fs.rmSync(path.join(out, 'overlays', '_template.html'), { force: true });

  /* 2. their settings, as a patch applied on top of config.js */
  const configPatch = Object.assign({}, client.config || {});
  if (client.channel) configPatch.channel = client.channel;

  fs.writeFileSync(path.join(out, 'js', 'client-config.js'),
    '/* Generated by make.js for "' + name + '". Edit clients/' + name +
    '.json and build again rather than editing this file. */\n' +
    '(function () {\n' +
    '  var patch = ' + JSON.stringify(configPatch, null, 2).replace(/\n/g, '\n  ') + ';\n' +
    '  function merge(target, source) {\n' +
    '    for (var key in source) {\n' +
    '      if (source[key] && typeof source[key] === "object" && !Array.isArray(source[key])) {\n' +
    '        target[key] = merge(target[key] || {}, source[key]);\n' +
    '      } else { target[key] = source[key]; }\n' +
    '    }\n' +
    '    return target;\n' +
    '  }\n' +
    '  merge(window.OverlayConfig, patch);\n' +
    '})();\n', 'utf8');

  /* 3. bake the skin into each overlay and load the settings patch */
  for (const file of OVERLAY_FILES) {
    const target = path.join(out, 'overlays', file);
    if (!fs.existsSync(target)) continue;
    patch(target, [
      [/var d = 'default';/, "var d = '" + skin + "';"],
      [/<script src="\.\.\/js\/config\.js"><\/script>/,
       '<script src="../js/config.js"></script>\n<script src="../js/client-config.js"></script>']
    ]);
  }

  /* 4. the control room shows their own sources and skin */
  const overlays = resolveOverlays(client);
  patch(path.join(out, 'index.html'), [
    [/<script src="js\/config\.js"><\/script>/,
     '<script src="js/config.js"></script>\n<script src="js/client-config.js"></script>\n' +
     '<script>window.ClientSkin = ' + JSON.stringify(skin) + '; window.ClientOverlays = ' +
     JSON.stringify(overlays) + ';</script>']
  ]);

  /* 5. instructions, written for the person receiving the folder */
  fs.writeFileSync(path.join(out, 'ΟΔΗΓΙΕΣ.md'), instructions(name, client, skin, overlays), 'utf8');

  /* 6. optional zip, using the tool Windows already has */
  let zipPath = null;
  if (options.zip) {
    zipPath = path.join(root, 'dist', name + '.zip');
    fs.rmSync(zipPath, { force: true });
    try {
      execFileSync('powershell', ['-NoProfile', '-Command',
        'Compress-Archive -Path "' + out + '\\*" -DestinationPath "' + zipPath + '"'],
        { stdio: 'pipe' });
    } catch (err) {
      console.warn('  ! Δεν έγινε το zip: ' + err.message);
      zipPath = null;
    }
  }

  console.log('  ✓ ' + name + '  →  dist/' + name + (zipPath ? '  +  dist/' + name + '.zip' : ''));
  console.log('    skin: ' + skin + '   overlays: ' + Object.keys(overlays).join(', '));
}

/* Merge the client's overlay choices over the defaults.

   An entry may carry "as" to name a second instance of the same overlay —
   that is how one person gets both a follower goal and a sub goal out of
   the single goal.html. */
function resolveOverlays(client) {
  const wanted = client.overlays || Object.keys(DEFAULT_OVERLAYS);
  const out = {};

  for (const entry of wanted) {
    const spec = typeof entry === 'string' ? { id: entry } : entry;
    const preset = DEFAULT_OVERLAYS[spec.id];

    const row = preset
      ? Object.assign({}, preset, spec)
      /* a one-off widget built for this person */
      : Object.assign({ file: 'overlays/' + spec.id + '.html', params: '', size: '—',
                        title: spec.id }, spec);

    row.base = spec.id;
    out[spec.as || spec.id] = row;
  }
  return out;
}

/* --- the handover note ---------------------------------------------------- */

function instructions(name, client, skin, overlays) {
  const who = client.displayName || name;
  const rows = Object.keys(overlays).map(function (id) {
    const o = overlays[id];
    const url = o.file + (o.params ? '?' + o.params : '');
    return '### ' + o.title + '\n\n' +
           '- **URL:** `' + url + '`\n' +
           '- **Μέγεθος:** ' + o.size + '\n';
  }).join('\n');

  return '# Overlays — ' + who + '\n\n' +
    'Skin: **' + skin + '**' + (client.channel ? '  ·  Κανάλι: **' + client.channel + '**' : '') + '\n\n' +
    '---\n\n' +
    '## Στήσιμο σε 3 βήματα\n\n' +
    '1. Διπλό κλικ στο **`start.cmd`**. Ανοίγει μια σελίδα με όλα τα overlays.\n' +
    '2. Για κάθε ένα που θέλεις: OBS → **Sources → + → Browser** → πάτα\n' +
    '   **Αντιγραφή** στη σελίδα και επικόλλησε στο πεδίο **URL**.\n' +
    '3. Βάλε το Width/Height που γράφει δίπλα.\n\n' +
    'Το παράθυρο με το `start.cmd` πρέπει να μένει ανοιχτό όσο κάνεις stream.\n' +
    'Αν το κλείσεις, τα overlays στο OBS θα βγουν λευκά.\n\n' +
    '> Εναλλακτικά, χωρίς το `start.cmd`: στο browser source τσέκαρε\n' +
    '> **Local file** και διάλεξε το αρχείο από τη λίστα πιο κάτω.\n\n' +
    '---\n\n' +
    '## Τα overlays σου\n\n' + rows + '\n' +
    '---\n\n' +
    '## Ρυθμίσεις OBS που βοηθάνε\n\n' +
    '- ✅ **Shutdown source when not visible**\n' +
    '- ✅ **Refresh browser when scene becomes active**\n' +
    '- ✅ **Control audio via OBS** (για να ακούγονται οι ήχοι των alerts)\n' +
    '- Το Alerts μην το κάνεις resize — άσ’ το 1920×1080.\n\n' +
    '---\n\n' +
    '## Ήχοι\n\n' +
    'Ρίξε mp3 στο `assets/sounds/` με ονόματα `follow.mp3`, `sub.mp3`,\n' +
    '`raid.mp3`, `cheer.mp3`, `tip.mp3`. Όποιο λείπει, απλώς δεν παίζει.\n\n' +
    '## Θέλεις αλλαγή;\n\n' +
    'Πες μου τι — χρώμα, θέση, κείμενα, νέο widget. Θα σου στείλω\n' +
    'καινούριο φάκελο· τα βήματα είναι τα ίδια.\n';
}

/* --- entry point ---------------------------------------------------------- */

/* keep skins/skins.json in step with the folders on disk */
try {
  const skinDir = path.join(root, 'skins');
  const names = fs.readdirSync(skinDir).filter(function (n) {
    return fs.existsSync(path.join(skinDir, n, 'skin.css'));
  }).sort(function (a, b) {
    return a === 'default' ? -1 : b === 'default' ? 1 : a.localeCompare(b);
  });
  fs.writeFileSync(path.join(skinDir, 'skins.json'), JSON.stringify(names, null, 2) + '\n', 'utf8');
} catch (err) { /* not fatal */ }

const args = process.argv.slice(2);
const options = { zip: args.includes('--zip') };
const names = args.filter(function (a) { return a.charAt(0) !== '-'; });

if (args.includes('--all')) {
  const dir = path.join(root, 'clients');
  const all = fs.existsSync(dir)
    ? fs.readdirSync(dir).filter(function (f) { return f.endsWith('.json') && f.charAt(0) !== '_'; })
    : [];
  if (!all.length) die('Δεν υπάρχει κανένα client στο clients/');
  console.log('');
  all.forEach(function (f) { build(path.basename(f, '.json'), options); });
  console.log('');
} else if (names.length) {
  console.log('');
  names.forEach(function (n) { build(n, options); });
  console.log('');
} else {
  console.log('\n  node make.js <όνομα> [--zip]   |   node make.js --all [--zip]\n');
  const dir = path.join(root, 'clients');
  if (fs.existsSync(dir)) {
    const all = fs.readdirSync(dir).filter(function (f) { return f.endsWith('.json'); });
    if (all.length) {
      console.log('  Διαθέσιμοι: ' + all.map(function (f) { return path.basename(f, '.json'); }).join(', ') + '\n');
    }
  }
}
